#[allow(unused_imports)]
use super::*;



/// A type which can delete rows from a table.
/// 
/// Related to [`DeleteCheck`](DeleteCheck) and [`DeleteImpl`](DeleteImpl).
/// 
/// These traits are not meant to be manually implemented,
/// see [`#[derive(Delete)]`](derive@Delete)
/// or [`#[sqly(delete)]`](docs::attr#delete)
/// instead.
pub trait Delete {
    /// The type representing the table which this query will operate on.
    /// 
    /// When generated with [`#[derive(Delete)]`](derive@Delete) this type is set by the [`#[sqly(table)]`](docs::attr#table) attribute.
    /// 
    /// When generated with [`#[sqly(delete)]`](docs::attr#delete) this type is set to the struct for which [`#[derive(Table)]`](derive@Table) was called.
    /// 
    /// When this type implements the [`Table`](Table) trait the [`Table::delete`](`Table::delete`) alias is made available, this type serves no other purpose.
    type Table;

    /// The query type for the operation to be executed.
    /// 
    /// This will be equal to one of the [`sqlx::query`](mod@sqlx::query) types.
    type Query<'a>
        where Self: 'a;

    /// Returns a query which deletes rows from the table according to the definition of this type.
    /// 
    /// This function is not meant to be manualy implemented,
    /// see [`#[derive(Delete)]`](derive@Delete)
    /// or [`#[sqly(delete)]`](docs::attr#delete)
    /// instead.
    fn delete(&self) -> Self::Query<'_>;
}



/// A type which has its [`Delete`](Delete) query checked at compile time.
/// 
/// This will be generated unless
/// [`#[sqly(unchecked)]`](docs::attr#codegen) is specified or
/// the default [`checked`](https://github.com/LMOORS30/sqly#features) feature is disabled.
/// 
/// This trait serves no further purpose.
pub trait DeleteCheck {
    /// Calls the [`sqlx::query_as!`] macro to perform the compile time check.
    /// 
    /// This function is not meant to be called and will panic if attempted.
    fn delete_check(&self) -> !;
}



/// A type which can delete rows from a table.
/// 
/// This is the implementation generated by [`#[sqly(Delete)]`](derive@Delete).
/// 
/// An implementation for [`Delete`](Delete) will be generated as
/// `Self::`[`delete_from`](DeleteImpl::delete_from)`(self.`[`delete_sql`](DeleteImpl::delete_sql)`())`
/// if possible.
pub trait DeleteImpl {
    /// See [`Delete::Table`](Delete::Table).
    type Table;

    /// See [`Delete::Query`](Delete::Query).
    type Query<'q, 'a>;

    /// The type from which the [`Delete::Query`](DeleteImpl::Query) is built.
    /// 
    /// This will be either `&'q str` or `(&'q str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    type From<'q, 'a>;

    /// The type generated by the macro derive.
    /// 
    /// This will be either `&'static str` or `(&'static str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    /// 
    /// If [`#[sqly(dynamic)]`](docs::attr#dynamic) was specified this will return an owned `String` instead,
    /// possibly wrapped in an `Option` (if a complete query might not be built),
    /// and the [`Delete`](Delete) implementation will not be available
    /// (because sqlx queries cannot store owned strings),
    /// this trait must be used instead.
    type Sql<'a>
        where Self: 'a;

    /// Returns the [`Self::Sql`](DeleteImpl::Sql) value generated by the macro derive.
    /// 
    /// Allows direct access to the SQL for further manipulation of the generated query.
    fn delete_sql(&self) -> Self::Sql<'_>;

    /// Returns the [`Delete::Query`](DeleteImpl::Query) value built from the given SQL value.
    /// 
    /// Assumes [`Self::From`](DeleteImpl::From) is based on the generated [`Self::Sql`](DeleteImpl::Sql).
    fn delete_from<'q, 'a>(query: Self::From<'q, 'a>) -> Self::Query<'q, 'a>;
}
