#[allow(unused_imports)]
use super::*;



/// A type which can delete rows from a table.
/// 
/// Serves as a wrapper for [`DeleteImpl`](DeleteImpl).
/// 
/// Related to [`DeleteCheck`](DeleteCheck).
pub trait Delete {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Delete)]`](derive@Delete)
    /// or [`#[sqly(delete)]`](docs::attr#delete)
    /// instead.
    const AUTOMATICALLY_DERIVED: ();

    /// The type representing the table which this query will operate on.
    /// 
    /// The [`Table::delete`](`Table::delete`) alias is available when this implements the [`Table`](Table) trait.
    type Table;

    /// The query type for the operation to be executed.
    /// 
    /// This will be one of the [`sqlx::query`](mod@sqlx::query) types.
    type Query<'a>
        where Self: 'a;

    /// Returns a query which deletes rows from the table according to the definition of this type.
    fn delete(&self) -> Self::Query<'_>;
}



/// A type which has its [`Delete`](Delete) query checked at compile time.
/// 
/// This will be generated unless
/// [`#[sqly(unchecked = query)]`](docs::attr#codegen) is specified or
/// the default [`checked`](https://github.com/LMOORS30/sqly#features) feature is disabled.
pub trait DeleteCheck {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Delete)]`](derive@Delete)
    /// or [`#[sqly(delete)]`](docs::attr#delete)
    /// instead.
    const AUTOMATICALLY_DERIVED: ();

    /// This function is not meant to be called and will panic if attempted.
    /// 
    /// Calls the [`sqlx::query_as!`] macro to perform the compile time check.
    /// 
    /// Calls [`sqlx::query_as_unchecked!`] instead if
    /// [`#[sqly(unchecked = types)]`](docs::attr#codegen) was specified.
    fn delete_check(&self) -> !;
}



/// A type which can delete rows from a table.
/// 
/// An implementation for [`Delete`](Delete) will be generated as
/// `Self::`[`delete_from`](DeleteImpl::delete_from)`(self.`[`delete_sql`](DeleteImpl::delete_sql)`())`
/// where possible.
pub trait DeleteImpl {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Delete)]`](derive@Delete)
    /// or [`#[sqly(delete)]`](docs::attr#delete)
    /// instead.
    const AUTOMATICALLY_DERIVED: ();

    /// See [`Delete::Table`](Delete::Table).
    type Table;

    /// See [`Delete::Query`](Delete::Query).
    type Query<'q, 'a>;

    /// The type from which the [`Delete::Query`](DeleteImpl::Query) is built.
    /// 
    /// This will be either `&'q str` or `(&'q str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    type From<'q, 'a>;

    /// The type generated by the macro derive.
    /// 
    /// This will be either `&'static str` or `(&'static str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    /// 
    /// If [`#[sqly(dynamic)]`](docs::attr#dynamic) was specified this will return an owned `String` instead,
    /// possibly wrapped in an `Option` (if a complete query might not be built),
    /// and the [`Delete`](Delete) implementation will not be available
    /// (because sqlx queries cannot store owned strings).
    type Sql<'a>
        where Self: 'a;

    /// Returns the [`Self::Sql`](DeleteImpl::Sql) value generated by the macro derive.
    /// 
    /// Allows direct access to the SQL for further manipulation of the generated query.
    fn delete_sql(&self) -> Self::Sql<'_>;

    /// Returns the [`Delete::Query`](DeleteImpl::Query) value built from the given SQL value.
    /// 
    /// Assumes [`Self::From`](DeleteImpl::From) is based on the generated [`Self::Sql`](DeleteImpl::Sql).
    fn delete_from<'q, 'a>(query: Self::From<'q, 'a>) -> Self::Query<'q, 'a>;
}
