#[allow(unused_imports)]
use super::*;



/// A type which can insert rows into a table.
/// 
/// Serves as a wrapper for [`InsertImpl`](InsertImpl).
/// 
/// Related to [`InsertCheck`](InsertCheck).
pub trait Insert {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Insert)]`](derive@Insert)
    /// or [`#[sqly(insert)]`](docs::attr#insert)
    /// instead.
    const AUTOMATICALLY_DERIVED: ();

    /// The type representing the table which this query will operate on.
    /// 
    /// The [`Table::insert`](`Table::insert`) alias is available when this implements the [`Table`](Table) trait.
    type Table;

    /// The query type for the operation to be executed.
    /// 
    /// This will be one of the [`sqlx::query`](mod@sqlx::query) types.
    type Query<'a>
        where Self: 'a;

    /// Returns a query which inserts rows into the table according to the definition of this type.
    fn insert(&self) -> Self::Query<'_>;
}



/// A type which has its [`Insert`](Insert) query checked at compile time.
/// 
/// This will be generated unless
/// [`#[sqly(unchecked = query)]`](docs::attr#codegen) is specified or
/// the default [`checked`](https://github.com/LMOORS30/sqly#features) feature is disabled.
pub trait InsertCheck {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Insert)]`](derive@Insert)
    /// or [`#[sqly(insert)]`](docs::attr#insert)
    /// instead.
    const AUTOMATICALLY_DERIVED: ();

    /// This function is not meant to be called and will panic if attempted.
    /// 
    /// Calls the [`sqlx::query_as!`] macro to perform the compile time check.
    /// 
    /// Calls [`sqlx::query_as_unchecked!`] instead if
    /// [`#[sqly(unchecked = types)]`](docs::attr#codegen) was specified.
    fn insert_check(&self) -> !;
}



/// A type which can insert rows into a table.
/// 
/// An implementation for [`Insert`](Insert) will be generated as
/// `Self::`[`insert_from`](InsertImpl::insert_from)`(self.`[`insert_sql`](InsertImpl::insert_sql)`())`
/// where possible.
pub trait InsertImpl {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Insert)]`](derive@Insert)
    /// or [`#[sqly(insert)]`](docs::attr#insert)
    /// instead.
    const AUTOMATICALLY_DERIVED: ();

    /// See [`Insert::Table`](Insert::Table).
    type Table;

    /// See [`Insert::Query`](Insert::Query).
    type Query<'q, 'a>;

    /// The type from which the [`Insert::Query`](InsertImpl::Query) is built.
    /// 
    /// This will be either `&'q str` or `(&'q str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    type From<'q, 'a>;

    /// The type generated by the macro derive.
    /// 
    /// This will be either `&'static str` or `(&'static str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    /// 
    /// If [`#[sqly(dynamic)]`](docs::attr#dynamic) was specified this will return an owned `String` instead,
    /// possibly wrapped in an `Option` (if a complete query might not be built),
    /// and the [`Insert`](Insert) implementation will not be available
    /// (because sqlx queries cannot store owned strings).
    type Sql<'a>
        where Self: 'a;

    /// Returns the [`Self::Sql`](InsertImpl::Sql) value generated by the macro derive.
    /// 
    /// Allows direct access to the SQL for further manipulation of the generated query.
    fn insert_sql(&self) -> Self::Sql<'_>;

    /// Returns the [`Insert::Query`](InsertImpl::Query) value built from the given SQL value.
    /// 
    /// Assumes [`Self::From`](InsertImpl::From) is based on the generated [`Self::Sql`](InsertImpl::Sql).
    fn insert_from<'q, 'a>(query: Self::From<'q, 'a>) -> Self::Query<'q, 'a>;
}
