#[allow(unused_imports)]
use super::*;



/// A type which can select rows from a table.
/// 
/// Related to [`SelectCheck`](SelectCheck) and [`SelectImpl`](SelectImpl).
/// 
/// These traits are not meant to be manually implemented,
/// see [`#[derive(Select)]`](derive@Select)
/// or [`#[sqly(select)]`](docs::attr#select)
/// instead.
pub trait Select {
    /// The type representing the table which this query will operate on.
    /// 
    /// When generated with [`#[derive(Select)]`](derive@Select) this type is set by the [`#[sqly(table)]`](docs::attr#table) attribute.
    /// 
    /// When generated with [`#[sqly(select)]`](docs::attr#select) this type is set to the struct for which [`#[derive(Table)]`](derive@Table) was called.
    /// 
    /// When this type implements the [`Table`](Table) trait the [`Table::select`](`Table::select`) alias is made available, this type serves no other purpose.
    type Table;

    /// The query type for the operation to be executed.
    /// 
    /// This will be equal to [`sqlx::query::Map`], with the `DB` type defined by the features enabled for this crate (see [Features](https://github.com/LMOORS30/sqly#features)).
    type Query<'a>
        where Self: 'a;

    /// Returns a query which selects rows from the table according to the definition of this type.
    /// 
    /// This function is not meant to be manualy implemented,
    /// see [`#[derive(Select)]`](derive@Select)
    /// or [`#[sqly(select)]`](docs::attr#select)
    /// instead.
    fn select(&self) -> Self::Query<'_>;
}



/// A type which has its [`Select`](Select) query checked at compile time.
/// 
/// This will be generated unless
/// [`#[sqly(unchecked)]`](docs::attr#dev-attributes) is specified or
/// the default [`checked`](https://github.com/LMOORS30/sqly#features) feature is disabled.
/// 
/// This trait serves no further purpose.
pub trait SelectCheck {
    /// Calls the [`sqlx::query_as!`] macro to perform the compile time check.
    /// 
    /// The result is not returned, this function is not meant to be called.
    fn select_check(&self);
}



/// A type which can select rows from a table.
/// 
/// This is the implementation generated by the macro derive.
/// 
/// An implementation for [`Select`](Select) will be generated as
/// `Self::`[`select_from`](SelectImpl::select_from)`(self.`[`select_sql`](SelectImpl::select_sql)`())`.
pub trait SelectImpl {
    /// See [`Select::Table`](Select::Table).
    type Table;

    /// See [`Select::Query`](Select::Query).
    type Query<'q, 'a>;

    /// The type from which the [`Select::Query`](SelectImpl::Query) is built.
    /// 
    /// This will be either `&'q str` or `(&'q str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    type From<'q, 'a>;

    /// The type generated by the macro derive.
    /// 
    /// This will be either `&'static str` or `(&'static str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    type Sql<'a>
        where Self: 'a;

    /// Returns the [`Self::Sql`](SelectImpl::Sql) value generated by the macro derive.
    /// 
    /// Allows direct access to the SQL for further manipulation of the generated query.
    fn select_sql(&self) -> Self::Sql<'_>;

    /// Returns the [`Select::Query`](SelectImpl::Query) value built from the given SQL value.
    /// 
    /// Assumes [`Self::From`](SelectImpl::From) is based on the generated [`Self::Sql`](SelectImpl::Sql).
    fn select_from<'q, 'a>(query: Self::From<'q, 'a>) -> Self::Query<'q, 'a>;
}
