#[allow(unused_imports)]
use super::*;



/// A type which can select rows from a table.
/// 
/// Related to [`SelectCheck`](SelectCheck) and [`SelectImpl`](SelectImpl).
/// 
/// These traits are not meant to be manually implemented,
/// see [`#[derive(Select)]`](derive@Select)
/// or [`#[sqly(select)]`](docs::attr#select)
/// instead.
pub trait Select {
    /// The type representing the table which this query will operate on.
    /// 
    /// When this type implements the [`Table`](Table) trait the [`Table::select`](`Table::select`) alias is made available, this type serves no other purpose.
    type Table;

    /// The query type for the operation to be executed.
    /// 
    /// This will be one of the [`sqlx::query`](mod@sqlx::query) types.
    type Query<'a>
        where Self: 'a;

    /// Returns a query which selects rows from the table according to the definition of this type.
    /// 
    /// This function is not meant to be manualy implemented,
    /// see [`#[derive(Select)]`](derive@Select)
    /// or [`#[sqly(select)]`](docs::attr#select)
    /// instead.
    fn select(&self) -> Self::Query<'_>;
}



/// A type which has its [`Select`](Select) query checked at compile time.
/// 
/// This will be generated unless
/// [`#[sqly(unchecked = query)]`](docs::attr#codegen) is specified or
/// the default [`checked`](https://github.com/LMOORS30/sqly#features) feature is disabled.
/// 
/// This trait serves no further purpose.
pub trait SelectCheck {
    /// Calls the [`sqlx::query_as!`] macro to perform the compile time check.
    /// 
    /// Calls [`sqlx::query_as_unchecked!`] instead if
    /// [`#[sqly(unchecked = types)]`](docs::attr#codegen) was specified.
    /// 
    /// This function is not meant to be called and will panic if attempted.
    fn select_check(&self) -> !;
}



/// A type which can select rows from a table.
/// 
/// This is the implementation generated by [`#[sqly(Select)]`](derive@Select).
/// 
/// An implementation for [`Select`](Select) will be generated as
/// `Self::`[`select_from`](SelectImpl::select_from)`(self.`[`select_sql`](SelectImpl::select_sql)`())`
/// if possible.
pub trait SelectImpl {
    /// See [`Select::Table`](Select::Table).
    type Table;

    /// See [`Select::Query`](Select::Query).
    type Query<'q, 'a>;

    /// The type from which the [`Select::Query`](SelectImpl::Query) is built.
    /// 
    /// This will be either `&'q str` or `(&'q str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    type From<'q, 'a>;

    /// The type generated by the macro derive.
    /// 
    /// This will be either `&'static str` or `(&'static str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    /// 
    /// If [`#[sqly(dynamic)]`](docs::attr#dynamic) was specified this will return an owned `String` instead,
    /// possibly wrapped in an `Option` (if a complete query might not be built),
    /// and the [`Select`](Select) implementation will not be available
    /// (because sqlx queries cannot store owned strings),
    /// this trait must be used instead.
    type Sql<'a>
        where Self: 'a;

    /// Returns the [`Self::Sql`](SelectImpl::Sql) value generated by the macro derive.
    /// 
    /// Allows direct access to the SQL for further manipulation of the generated query.
    fn select_sql(&self) -> Self::Sql<'_>;

    /// Returns the [`Select::Query`](SelectImpl::Query) value built from the given SQL value.
    /// 
    /// Assumes [`Self::From`](SelectImpl::From) is based on the generated [`Self::Sql`](SelectImpl::Sql).
    fn select_from<'q, 'a>(query: Self::From<'q, 'a>) -> Self::Query<'q, 'a>;
}
