#[allow(unused_imports)]
use super::*;



/// A type which can update rows in a table.
/// 
/// Related to [`UpdateCheck`](UpdateCheck) and [`UpdateImpl`](UpdateImpl).
/// 
/// These traits are not meant to be manually implemented,
/// see [`#[derive(Update)]`](derive@Update)
/// or [`#[sqly(update)]`](docs::attr#update)
/// instead.
pub trait Update {
    /// The type representing the table which this query will operate on.
    /// 
    /// When this type implements the [`Table`](Table) trait the [`Table::update`](`Table::update`) alias is made available, this type serves no other purpose.
    type Table;

    /// The query type for the operation to be executed.
    /// 
    /// This will be one of the [`sqlx::query`](mod@sqlx::query) types.
    type Query<'a>
        where Self: 'a;

    /// Returns a query which updates rows in the table according to the definition of this type.
    /// 
    /// This function is not meant to be manualy implemented,
    /// see [`#[derive(Update)]`](derive@Update)
    /// or [`#[sqly(update)]`](docs::attr#update)
    /// instead.
    fn update(&self) -> Self::Query<'_>;
}



/// A type which has its [`Update`](Update) query checked at compile time.
/// 
/// This will be generated unless
/// [`#[sqly(unchecked = query)]`](docs::attr#codegen) is specified or
/// the default [`checked`](https://github.com/LMOORS30/sqly#features) feature is disabled.
/// 
/// This trait serves no further purpose.
pub trait UpdateCheck {
    /// Calls the [`sqlx::query_as!`] macro to perform the compile time check.
    /// 
    /// Calls [`sqlx::query_as_unchecked!`] instead if
    /// [`#[sqly(unchecked = types)]`](docs::attr#codegen) was specified.
    /// 
    /// This function is not meant to be called and will panic if attempted.
    fn update_check(&self) -> !;
}



/// A type which can update rows in a table.
/// 
/// This is the implementation generated by [`#[sqly(Update)]`](derive@Update).
/// 
/// An implementation for [`Update`](Update) will be generated as
/// `Self::`[`update_from`](UpdateImpl::update_from)`(self.`[`update_sql`](UpdateImpl::update_sql)`())`
/// if possible.
pub trait UpdateImpl {
    /// See [`Update::Table`](Update::Table).
    type Table;

    /// See [`Update::Query`](Update::Query).
    type Query<'q, 'a>;

    /// The type from which the [`Update::Query`](UpdateImpl::Query) is built.
    /// 
    /// This will be either `&'q str` or `(&'q str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    type From<'q, 'a>;

    /// The type generated by the macro derive.
    /// 
    /// This will be either `&'static str` or `(&'static str, Result<`[`sqlx::Arguments`]`<'a>>)`.
    /// 
    /// If [`#[sqly(dynamic)]`](docs::attr#dynamic) was specified this will return an owned `String` instead,
    /// possibly wrapped in an `Option` (if a complete query might not be built),
    /// and the [`Update`](Update) implementation will not be available
    /// (because sqlx queries cannot store owned strings),
    /// this trait must be used instead.
    type Sql<'a>
        where Self: 'a;

    /// Returns the [`Self::Sql`](UpdateImpl::Sql) value generated by the macro derive.
    /// 
    /// Allows direct access to the SQL for further manipulation of the generated query.
    fn update_sql(&self) -> Self::Sql<'_>;

    /// Returns the [`Update::Query`](UpdateImpl::Query) value built from the given SQL value.
    /// 
    /// Assumes [`Self::From`](UpdateImpl::From) is based on the generated [`Self::Sql`](UpdateImpl::Sql).
    fn update_from<'q, 'a>(query: Self::From<'q, 'a>) -> Self::Query<'q, 'a>;
}
