#[allow(unused_imports)]
use super::*;

mod delete;
mod insert;
mod select;
mod update;

pub use delete::*;
pub use insert::*;
pub use select::*;
pub use update::*;



/// A type which represents a database table.
/// 
/// Related to [`Check`](Check) and [`Flat`](Flat).
/// 
/// Serves as an alias to the implementation of other traits
/// ([`Delete`](Delete), [`Insert`](Insert), [`Select`](Select), [`Update`](Update))
/// where `<Table = Self>`.
pub trait Table {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Table)]`](derive@Table) instead.
    const AUTOMATICALLY_DERIVED: ();

    /// Delegates to [`Delete::delete`](Delete::delete).
    fn delete<R>(row: &R) -> R::Query<'_>
    where R: Delete<Table = Self> {
        row.delete()
    }

    /// Delegates to [`Insert::insert`](Insert::insert).
    fn insert<R>(row: &R) -> R::Query<'_>
    where R: Insert<Table = Self> {
        row.insert()
    }

    /// Delegates to [`Select::select`](Select::select).
    fn select<R>(row: &R) -> R::Query<'_>
    where R: Select<Table = Self> {
        row.select()
    }

    /// Delegates to [`Update::update`](Update::update).
    fn update<R>(row: &R) -> R::Query<'_>
    where R: Update<Table = Self> {
        row.update()
    }

}



/// A [`Table`](Table) which has its columns checked at compile time.
/// 
/// This will be generated unless
/// [`#[sqly(unchecked = query)]`](docs::attr#codegen) is specified or
/// the default [`checked`](https://github.com/LMOORS30/sqly#features) feature is disabled.
pub trait Check {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Table)]`](derive@Table) instead.
    const AUTOMATICALLY_DERIVED: ();

    /// This function is not meant to be called and will panic if attempted.
    /// 
    /// Calls the [`sqlx::query_as!`] macro to perform the compile time check.
    /// 
    /// Calls [`sqlx::query_as_unchecked!`] instead if
    /// [`#[sqly(unchecked = types)]`](docs::attr#codegen) was specified.
    fn check(&self) -> !;
}



/// A [`Table`](Table) with a flattened representation.
/// 
/// This will be generated by [`#[sqly(flat)]`](docs::attr#flat) if specified.
/// 
/// Implements [`From<Self::Flat>`](Flat::Flat)&ensp;if&ensp;[`#[sqly(from_flat)]`](docs::attr#flat) was specified.
/// 
/// Implements [`TryFrom<Self::Flat>`](Flat::Flat)&ensp;if&ensp;[`#[sqly(try_from_flat)]`](docs::attr#flat) was specified.
pub trait Flat {
    /// This trait is not meant to be manually implemented,
    /// see [`#[derive(Table)]`](derive@Table) instead.
    const AUTOMATICALLY_DERIVED: ();

    /// The flattened representation of this table.
    /// 
    /// Can be used with the [`sqlx::query_as!`] macro and [`sqlx::FromRow`] derive (generates `non_snake_case` warnings).
    /// 
    /// Already implements [`sqlx::FromRow`]&ensp;if&ensp;[`#[sqly(flat_row)]`](docs::attr#flat) was specified (prevents `non_snake_case` warnings).
    type Flat;
}
