mod macros;
mod rules;
mod traits;

/// Imports.
pub mod derive {
    pub use super::Table;
    pub use super::Delete;
    pub use super::Insert;
    pub use super::Select;
    pub use super::Update;
}

/// Documentation.
pub mod docs {
    #[allow(unused_imports)]
    use super::*;
    #[doc = include_str!("docs/documentation.md")]
    pub mod attr {
        #[allow(unused_imports)]
        use super::*;
        #[doc = include_str!("docs/notation.md")]
        pub mod note {}
    }
}

/// A type which has its query checked at compile time.
/// 
/// This trait is not meant to be manually implemented,
/// it will be generated the derive macros
/// unless [`#[sqly(unchecked)]`](docs::attr#dev-attributes) is specified or
/// the `unchecked` [feature](https://github.com/LMOORS30/sqly#features) is enabled.
/// 
/// This trait serves no further purpose.
pub trait Checked {
    /// no-op
    fn check(&self);
}

/// A type with a flattened representation.
/// 
/// This trait is not meant to be manually implemented,
/// it will be generated by [`#[sqly(flat)]`](docs::attr#flat) if specified.
pub trait Flat: Table + From<Self::Flat> {
    /// The flattened representation of this table.
    /// 
    /// The fields of this type match the SQL `SELECT` list of generated queries.
    type Flat: for <'r> sqlx::FromRow<'r, <<Self as Table>::DB as sqlx::Database>::Row>;
}

pub use macros::*;
pub use traits::*;
